### ISSUE TITLE
竟然获取了我的内网IP？

### ISSUE THREAD

**Issue by bao3** [anrip/dnspod-shell#18]
我的网卡有 10.16.0.0 IP，有公网IP，可是这个脚本居然只获得了 10.16 开头的IP。

**Comment by Fengtalk** [comment]
获取到了192.168.50.*的内网IP地址。

**Comment by ProfFan** [comment]
请指出你们的IP，可以隐去最后部分

**Comment by zcq100** [comment]
在多个网络接口下经常不能正确获取ip，建议通过第三方网站获取的为准。

**Comment by ProfFan** [comment]
可以考虑增加配置文件项目。最近没时间维护，欢迎PR

**Comment by zcq100** [comment]
PR了

**Comment by yimt** [comment]
@fengtalk 我也获取了我的内网IP，后来你是怎么处理的？

**Comment by yjy11994** [comment]
我这里路由器居然无法拨号，只能通过光猫拨号，结果就只获取到内网地址... 尴尬...
