### ISSUE TITLE
更新时@和其他域名都可以更新，唯独*的通配符更新失败

### ISSUE THREAD

**Issue by yunnl** [anrip/dnspod-shell#30]
更新时@和其他域名都可以更新，唯独*的通配符更新失败

能不能帮忙看一下是什么问题呢？

如果我要更新test.baidu.com，配置文件里是不是应该写
arDdnsCheck "baidu.com" "test" 
这样？

**Comment by yunnl** [comment]
> 建议你 更新一个 二级域名，将*记录cname到该二级域名

厉害了Word哥，这个办法很给力！

**Comment by duanego** [comment]
已提交修复代码，合入之后这个issue可以关了

**Comment by anrip** [comment]
已解决
