### ISSUE TITLE
近期准备重写一下这个脚本

### ISSUE THREAD

**Issue by anrip** [anrip/dnspod-shell#31]
看到很多人依旧在使用这个脚本，但是这个脚本已经历时3年未更新。其中更是使用了 wget 的ssl模块，不知道大家认为是否有必要更改为 curl ？

**Comment by q629988171** [comment]
结论：没有必要重写
原因：

- 一直在更新（最近一次更新在一年前）
- 已经很好用，不知道出于什么原因要重写
- 每个人使用环境不同不可能满足所有人（会变得囊肿复杂难以维护）
- 比如我用的极路由wget不支持SSL，我不会去添加这个支持（成本高），而是直接修改为CURL，但是有的人又没有CURL。怎样去权衡到底以Wget为主还是Curl，可能会因为这个事讨论半天。这个事情还有个方案就是先检查你的wget，如果不支持ssl就换成curl。
- 获取公网IP的方法看到有建议改成通过ip138获取，假设这个ip138故障就会影响公网IP获取（目前获取IP方式不依赖第三方）。当然也可以做一些判断准备两套方案。
- 然后这个项目就会变得越来越囊肿
- 我们只做BUG修复就好或者关键更新，比如检测IP的机制不重复提交，哪些因为环境差异的更新需求就任其自行发展

以上观点根据两个原则做出：
1. 最小化影响
2. 物尽其用

​

**Comment by 1368129224** [comment]
多拨用户好像无法使用
