### ISSUE TITLE
已经联网却无法更新Update Failed! Please check your network.

### ISSUE THREAD

**Issue by 1368129224** [anrip/dnspod-shell#32]
Base on LEDE/OpenWrt (18.12, r4592, 2018-12-13-git-a1945fb)
Linux
Updating Domain: myDomain
hostIP: *.210.157.95 *.210.157.4 *.210.157.124
lastIP: *.210.157.124
Update Failed! Please check your network.
多拨用户，不知道有没有影响。
麻烦指导一下，谢谢！

**Comment by sealionking** [comment]
我的也是同样的错误，没有多拨

**Comment by ProfFan** [comment]
bash tracing log

**Comment by sealionking** [comment]
traceroute aliyun.com
traceroute to aliyun.com (106.11.248.82), 30 hops max, 60 byte packets
 1  RT-N56U_B1.lan (192.168.123.1)  0.565 ms  0.531 ms  0.504 ms
 2  113.65.4.1 (113.65.4.1)  7.497 ms  7.632 ms  7.748 ms
 3  218.19.217.249 (218.19.217.249)  2.636 ms 121.8.134.121 (121.8.134.121)  3.800 ms 121.8.132.85 (121.8.132.85)  5.953 ms
 4  61.144.2.21 (61.144.2.21)  7.152 ms  7.164 ms 61.140.80.89 (61.140.80.89)  7.035 ms
 5  202.101.63.57 (202.101.63.57)  27.645 ms 61.152.86.209 (61.152.86.209)  27.649 ms 202.101.63.57 (202.101.63.57)  27.592 ms
 6  101.95.207.242 (101.95.207.242)  28.304 ms 124.74.166.142 (124.74.166.142)  26.574 ms 101.95.206.2 (101.95.206.2)  28.556 ms
 7  * * *
 8  101.95.211.122 (101.95.211.122)  28.526 ms 101.95.211.118 (101.95.211.118)  29.777 ms 180.163.38.30 (180.163.38.30)  28.403 ms
 9  * * 140.205.50.242 (140.205.50.242)  29.379 ms
10  106.11.75.234 (106.11.75.234)  30.601 ms * *
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
[root@localhost ArDNSPod]#

**Comment by ProfFan** [comment]
`bash -x`

**Comment by sealionking** [comment]
我的问题解决了，因为路由器刷了一个定制的固件，现在固件里面自己有ArDNSPod的shell，路由器自己会更新domains的ip。

麻烦了。

**Comment by sealionking** [comment]
换了个路由器又不行了
