### ISSUE TITLE
为什么不用nvram get wan0_ipaddr获取ip地址呢

### ISSUE THREAD

**Issue by luooyii** [anrip/dnspod-shell#34]
如题，为何要通过第三方获取ip地址，如果members.3322.org这个网址挂了怎么办

**Comment by ulpyuxa** [comment]
刚试了下，nvram好像不是所有系统都有这个命令，像OpenWrt就没有。
所以建议使用ifconfig命令，基本上路由器的系统都有这个命令，只不过唯一的缺点就是需要自己找到有公网ip的 interface，有的interface 是etho0, 有些是ppp0。
ifconfig eth0 | grep "inet addr" | cut -d ':' -f 2 | cut -d ' ' -f 1

**Comment by lqzhgood** [comment]
如果是内网呢~ 不通过第三方怎么拿公网ip

**Comment by anrip** [comment]
会遇到各种各样的需求，我之前是使用的dnspod的api获取外部ip。
后来大家提交了使用ip route获取的方式，各有优劣，可以自己选用。

至于nvram通用性不行，故而不采用此方式，您可以自行更改获取方式
