### ISSUE TITLE
Get Record Info Failed!

### ISSUE THREAD

**Issue by xiamenma** [anrip/dnspod-shell#38]
2019-11-26
废弃修改资料、修改密码、修改邮箱、获取手机验证码四个用户相关接口
废弃D令牌验证相关参数
Domain.List、Record.List、Domain.Info、Record.Info四个接口新增返回字段
优化 API 调用频次限制，并增加频次说明。
调整了有问题的错误码

**Comment by xcoco** [comment]
`domainID=$(arApiPost "Domain.Info" "domain=$1")
    domainID=$(echo $domainID | sed 's/.*{"id":"\([0-9]*\)".*/\1/')`

update

`domainID=$(arApiPost "Domain.Info" "domain=${1}")
    domainID=$(echo $domainID | sed 's/.*"id":"\([0-9]*\)".*/\1/')`

**Comment by Tdmy** [comment]
> `domainID=$(echo $domainID | sed 's/.*{"id":"\([0-9]*\)".*/\1/')`
> 
> 更新
> 
> `domainID=$(echo $domainID | sed 's/.*"id":"\([0-9]*\)".*/\1/')`

请问这是什么意思！

**Comment by anrip** [comment]
已更新到 V6.0 ，测试后请反馈
