### ISSUE TITLE
12月31日 使用脚本 提示  Get Record Info Failed!

### ISSUE THREAD

**Issue by Tdmy** [anrip/dnspod-shell#41]
root@raspbian:/home/pi/ddns# ./ddnspod.sh
Type: A
OS: Linux
Address: 115.221.12.117
Updating Domain: .Timcc.xyz
hostIP: 115.221.12.117
Get Record Info Failed!

**Comment by anrip** [comment]
已更新到 V6.0 ，测试后请反馈

**Comment by openlives** [comment]
原来就解析某个域名xyz.com,配置文件是
 arDdnsCheck "xyz.com" "" 
只需在DNSPOD  添加一条主机记录@ 记录类型为A，现在要添加一条主机记录www 记录类型为A，才会解析成功 ，否则一直是 Get Record Info Failed!

**Comment by RebelliousWhiz** [comment]
实测环境：本机解析 pma.xxx.xxx, www.xxx.xxx, @.xxx.xxx, *.xxx.xxx

配置：

arDdnsCheck "xxx.xxx" "www"
arDdnsCheck "xxx.xxx" "pma"
arDdnsCheck "xxx.xxx" "*"
arDdnsCheck "xxx.xxx" ""

经过实测，不成功。

log:

Updating Domain: www.xxx.xxx
Host Ip: 58.222.222.222
lastIP: 58.222.222.222
Last IP is the same as current IP!
Updating Domain: pma.xxx.xxx
Host Ip: 58.222.222.222
lastIP: 58.222.222.222
Last IP is the same as current IP!
Updating Domain: *.xxx.xxx
Host Ip: 58.222.222.222
lastIP: 58.222.222.222
Last IP is the same as current IP!
Updating Domain: .xxx.xxx
Host Ip: 58.222.222.222
lastIP: 58.222.222.222
Last IP is the same as current IP!


进dnspod，其他解析均正常，唯有@的A记录未成功修改。
