### ISSUE TITLE
脚本在openwrt上运行错误

### ISSUE THREAD

**Issue by jezhang** [anrip/dnspod-shell#42]
root@OpenWrt:~/ArDNSPod# ./ddnspod.sh
Updating Domain: x.yz.com
hostIP: 49.171.63.47
lastIP: 49.171.63.147
wget: bad address 'completed'
wget: bad address 'completed'
Update Failed! Please check your network.

**Comment by anrip** [comment]
已更新到 V6.0 ，测试后请反馈
