### ISSUE TITLE
请问 ipv6 怎么用？

### ISSUE THREAD

**Issue by jacdy** [anrip/dnspod-shell#47]
试一下，看到更新上去的是 ipv4 的址址，如果使用才能只把 ipv6 更新到 DDNS 中

**Comment by anrip** [comment]
可以把本地获取ipv4的代码删除，使用远程获取

**Comment by liuliping0315** [comment]
水平不够，改不动了，用大佬现成的，支持v6

https://github.com/imki911/ArDNSPod

**Comment by anrip** [comment]
已支持
