### ISSUE TITLE
返回错误Get Record Info Failed!

### ISSUE THREAD

**Issue by QweJay** [anrip/dnspod-shell#50]
x-wrt路由上提示 Error relocating /usr/bin/wget: ENGINE_load_builtin_engines: symbol not found

**Comment by anrip** [comment]
检查是否支持ssl

**Comment by q629988171** [comment]
> 检查是否支持ssl

我也遇到报错:

1. wget: unrecognized option: output-document=-
2. "Get Record Info Failed!"

环境: 
OpenWrt 18.06.8 r7989-82fbd85747
dnspod-shell-20200805

第一个错误, 在移除"output-document=-" 后解决
第二个错误, print 信息:

wget --quiet --no-check-certificate --user-agent=AnripDdns/6.0.0(mail@anrip.com) --post-data login_token=00000,0000000000000000000000000000000&format=json&domain_id=wget --quiet --no-check-certificate --user-agent=AnripDdns/6.0.0(mail@anrip.com) --post-data login_token=00000,0000000000000000000000000000000&format=json&domain=qq.com https://dnsapi.cn/Domain.Info&record_id=wget --quiet --no-check-certificate --user-agent=AnripDdns/6.0.0(mail@anrip.com) --post-data login_token=00000,0000000000000000000000000000000&format=json&domain_id=wget --quiet --no-check-certificate --user-agent=AnripDdns/6.0.0(mail@anrip.com) --post-data login_token=00000,0000000000000000000000000000000&format=json&domain=qq.com https://dnsapi.cn/Domain.Info&sub_domain=pc&record_type=A https://dnsapi.cn/Record.List https://dnsapi.cn/Record.Info

可以看到post的数据是错误的, 不完整的. 至于为什么会产生错误的结构数据, 我没有继续调试.

第二个错误解决方案:

确保安装了curl, 然后修改 ardnspod(curl 优先调用, 避免使用wget):

    if type curl >/dev/null 2>&1; then
        curl -s -A $agent -d $params $apiurl    
    else        
        wget --quiet --no-check-certificate --user-agent=$agent --post-data $params $apiurl        
    fi

当然这个方案是个临时解决方案, 最终还是要适配wget, 毕竟wget是openwrt自带 , 而curl 需要另外安装.
