### ISSUE TITLE
2020年02月06日DNSPod  API 升级 这次更新是否需要适配？

### ISSUE THREAD

**Issue by SaSmTi** [anrip/dnspod-shell#51]
2020年02月06日DNSPod  API 升级 这次更新是否需要适配？

**Comment by SaSmTi** [comment]
User.Details接口：返回的telephone字段加密中间四位数字；代理身份的用户返回agent字段，非代理身份的用户不返回agent字段
Domain.Create接口：返回的domain.id字段类型为字符串
Domain.List接口：返回的info.*字段类型统一为数字（info.domain_total, info.all_total, info.mine_total, info.share_total, info.vip_total, info.ismark_total, info.pause_total, info.error_total, info.lock_total, info.spam_total, info.vip_expire, info.share_out_total）
Record.List接口和Record.Info接口：返回的domain.id字段根据传入参数不同返回不同类型（保持与2019.11.26发布前的接口逻辑一致，当传入合法domain_id参数时，domain.id字段类型为数字，当未传入合法domain_id但传入了合法domain参数时，domain.id字段类型为字符串）
Batch.Domain.Create、Batch.Record.Create接口、Batch.Record.Modify接口：返回的job_id字段类型为字符串

**Comment by anrip** [comment]
无需适配
