### ISSUE TITLE
求助crontab命令怎么写，我 */5 * * * *  /root/ddnspod.sh  每5分钟执行行一此，无效

### ISSUE THREAD

**Issue by liuzhiping138** [anrip/dnspod-shell#54]
求助crontab命令怎么写，我 */5 * * * *  /root/ddnspod.sh  每5分钟执行行一此，无效

**Comment by anrip** [comment]
直接运行可以么?

**Comment by 10935336** [comment]
遇到同样的问题，文件改了名
crontab内
`0 */1 * * * cd /nvme/v6ddns/moe && /bin/bash ddnspodmoe.sh>>moe.log`
log文件内显示
```
Type: AAAA
OS: Linux
Address: 
Updating Domain: xxxxxxxx
hostIP: 
lastIP: xxxxxxxxxxxxxx
{"status":{"code":"17","message":"\u8bb0\u5f55\u7684\u503c\u4e0d\u6b63\u786e","created_at":"2020-08-14 18:00:03"}}
```
直接运行`ddnspodmoe.sh`或`/bin/bash ddnspodmoe.sh>>moe.log`均正常

**Comment by liuliping0315** [comment]
*15 * * * * root ddnspod.sh
我的是这样的，十五分钟一次，你怎么那么多斜杠

**Comment by Rambin** [comment]
> 求助crontab命令怎么写，我 */5 * * * *  /root/ddnspod.sh  每5分钟执行行一此，无效

应该是0/5吧？除以5是0的分钟数
