### ISSUE TITLE
建议在域名更新参数增加record_id，用于更新同一subdomain不同的解析记录

### ISSUE THREAD

**Issue by feheadls** [anrip/dnspod-shell#61]
dnspod.cn如果要对同一个子域名解析多个A记录，或者AAAA记录，服务端就要将子域名配置多条解析记录，API更新参数中只有子域名subdomain的话，只能更新服务端该子域名的首条解析记录，无法对首条后的记录进行更新。

举个例子，在服务端配置两条主机记录test，第一条为A记录，第二条为AAAA记录，API提交记录更新只带上subdomain=test的话，只能更新服务器的A记录，无法更新第二条AAAA记录。如果API带上record_id参数，API提交record_id="第二条记录的ID”，就可以指定更新第二条AAAA记录。

这样运行两条脚本，就能实现IPV4/IPV6双栈动态解析，也可以一个域名记录指定多个IPV4地址，实现域名负载均衡（DNSPOD支持IPV4的负载均衡）

**Comment by anrip** [comment]
现在可以直接更新了
