### ISSUE TITLE
建议增加一键云运行脚本

### ISSUE THREAD

**Issue by Omoinemie** [anrip/dnspod-shell#65]
使用云脚本，不用将脚本下载到本地，通过定时wget或者curl一键运行，参数可以在带到命令中而不用修改文件，我今天openwrt更新系统结果下载的脚本没了，然后就连接不上机器了

**Comment by anrip** [comment]
下载命令丢了怎么办

----------

若海


--------------原始邮件--------------
发件人："ccminglove "<notifications@github.com&gt;;
发送时间：2021年3月4日(星期四) 晚上8:15
收件人："anrip/dnspod-shell" <dnspod-shell@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[anrip/dnspod-shell] 建议增加一键云运行脚本 (#65)
-----------------------------------

 

 
使用云脚本，不用将脚本下载到本地，通过定时wget或者curl一键运行，参数可以在带到命令中而不用修改文件，我今天openwrt更新系统结果下载的脚本没了，然后就连接不上机器了

**Comment by Omoinemie** [comment]
> 下载命令丢了怎么办
> […](#)
> ---------- 若海
> --------------原始邮件-------------- 发件人："ccminglove "<notifications@github.com&gt;; 发送时间：2021年3月4日(星期四) 晚上8:15 收件人："anrip/dnspod-shell" <dnspod-shell@noreply.github.com&gt;; 抄送："Subscribed "<subscribed@noreply.github.com&gt;; 主题：[anrip/dnspod-shell] 建议增加一键云运行脚本 (#65) ----------------------------------- 使用云脚本，不用将脚本下载到本地，通过定时wget或者curl一键运行，参数可以在带到命令中而不用修改文件，我今天openwrt更新系统结果下载的脚本没了，然后就连接不上机器了 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

有总比没有好吧

**Comment by Omoinemie** [comment]
像这样 ./ardnspod arToken="******,******************" recordType="A" domain="sub.domain.com"

**Comment by anrip** [comment]
本身就可以这样做的呀

```
. ./ardnspod
arToken="12345,7676f344eaeaea9074c123451234512d"
arDdnsCheck "test.org" "subdomain"
```

**Comment by Omoinemie** [comment]
可以写到readme里面

**Comment by anrip** [comment]
> 可以写到readme里面

你可以看下 `ddnspod.sh`，里面就是这3句话

**Comment by Omoinemie** [comment]
这没日志输出也不知道运行成功没有
![Snipaste_2021-03-05_11-47-22](https://user-images.githubusercontent.com/31991443/110064730-a9b32600-7da8-11eb-92b0-15fb60d41884.jpg)

**Comment by anrip** [comment]
你这肯定失败了，需要分为三行。第一行是导入脚本的语句，第二行设置账户，第三行执行循环任务

**Comment by anrip** [comment]
另外，请你认真阅读说明里面的小提示

**Comment by anrip** [comment]
给你个懒人脚本

```
# 下载脚本
curl https://raw.githubusercontent.com/anrip/dnspod-shell/master/ardnspod > ~/ardnspod 
# 写入配置
echo ”arToken=12345,7676f344eaeaea9074c123451234512d“ >>~/ardnspod
echo “arDdnsCheck test.org subdomain” >>~/ardnspod
# 执行任务
~/ardnspod
```
