### ISSUE TITLE
ipv6更新失败

### ISSUE THREAD

**Issue by dweey** [anrip/dnspod-shell#66]
![image](https://user-images.githubusercontent.com/10607347/110460009-a1404f80-8108-11eb-9030-b662602c7e90.png)

停留在这里
估摸着可能是是判断返回的是ip还是错误信息的地方有点问题

arDdnsRecordIp() {

    local errMsg

    local recordIp

    # Get Record Ip
    recordIp=$(arDdnsApi "Record.Info" "domain_id=$1&record_id=$2")
    recordIp=$(echo $recordIp | sed 's/.*,"value":"\([0-9a-fA-F\.\:]*\)".*/\1/')

    # Output Record Ip
    case "$recordIp" in
        [1-9]*)
            echo $recordIp
            return 0
        ;;
        *)
            errMsg=$(echo $recordIp | sed 's/.*"message":"\([^\"]*\)".*/\1/')
            echo "arDdnsRecordIp - $errMsg"
            return 1
        ;;
    esac

}

**Comment by anrip** [comment]
可能是因为没有兼容ipv6造成的

----------

若海


--------------原始邮件--------------
发件人："dweey "<notifications@github.com&gt;;
发送时间：2021年3月9日(星期二) 晚上6:59
收件人："anrip/dnspod-shell" <dnspod-shell@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[anrip/dnspod-shell] ipv6更新失败 (#66)
-----------------------------------

 

 

 
停留在这里
 估摸着可能是是判断返回的是ip还是错误信息的地方有点问题
 
arDdnsRecordIp() {
 local errMsg local recordIp # Get Record Ip recordIp=$(arDdnsApi "Record.Info" "domain_id=$1&amp;record_id=$2") recordIp=$(echo $recordIp | sed 's/.*,"value":"\([0-9a-fA-F\.\:]*\)".*/\1/') # Output Record Ip case "$recordIp" in     [1-9]*)         echo $recordIp         return 0     ;;     *)         errMsg=$(echo $recordIp | sed 's/.*"message":"\([^\"]*\)".*/\1/')         echo "arDdnsRecordIp - $errMsg"         return 1     ;; esac  
}

**Comment by anrip** [comment]
fixed
