### ISSUE TITLE
ipv6脚本更新bug

### ISSUE THREAD

**Issue by Omoinemie** [anrip/dnspod-shell#69]
两个v6 IP，正好更新不通的那一个
![Snipaste_2021-03-17_11-17-53](https://user-images.githubusercontent.com/31991443/111410076-07356400-8713-11eb-92aa-ef08d43ed403.jpg)

可采用在线获取IP的模式：
V4 URL: http://v4.ip.zxinc.org/getip
V6 URL: http://v6.ip.zxinc.org/getip

**Comment by Omoinemie** [comment]
`# Get WAN IPv6

arWanIp6() {

    local hostIp

    local lanIps="(^$)|(^::1$)|(^fe[8-9,A-F])"

    if [ -z "$hostIp" ]; then
        if type wget >/dev/null 2>&1; then
            hostIp=$(wget -q -O- http://v6.ip.zxinc.org/getip)
        else
            hostIp=$(curl -s http://v6.ip.zxinc.org/getip)
        fi
    fi

    if [ -z "$hostIp" ]; then
        echo "arWanIp6 - Can't get ip address"
        return 1
    fi

    if [ -z "$(echo $hostIp | grep -E '^[0-9a-fA-F:]+$')" ]; then
        echo "arWanIp6 - Invalid ip address"
        return 1
    fi

    echo $hostIp

}`

**Comment by anrip** [comment]
fixed
